mode: statefulset

config:
  receivers:
    jaeger: null
    prometheus: null
    zipkin: null

  exporters:
    otlp:
      endpoint: "tempo.zerofiltre-bootcamp.svc.cluster.local:4317"
      tls:
        insecure: true
    debug:
      verbosity: detailed
    otlphttp:
      endpoint: "http://loki-backend-gateway.zerofiltre-bootcamp.svc.cluster.local/otlp"
      headers:
        "X-Scope-OrgID": "bootcamp"

    prometheusremotewrite:
      endpoint: "http://prometheus-server.zerofiltre-bootcamp.svc.cluster.local/api/v1/write"
      tls:
        insecure: true

  service:
    pipelines:
      traces:
        receivers:
          - otlp
        processors:
          - batch
          - memory_limiter
        exporters:
          - otlp
      metrics:
        receivers:
          - otlp
        processors:
          - batch
          - memory_limiter
        exporters:
          - prometheusremotewrite
      logs:
        receivers:
          - otlp
        processors:
          - batch
          - memory_limiter
        exporters:
#          - debug
          - otlphttp
image:
  repository: "otel/opentelemetry-collector-contrib"

resources:
  requests:
    cpu: "0.1"
    memory: 50Mi
  limits:
    cpu: "0.1"
    memory: 50Mi
