kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false

alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

server:
  extraFlags:
    - web.enable-remote-write-receiver
